# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a58884c6a9b5b73eedc087cbdd9e1cade9b183675be2a77c89393d301b63f8edb53743432ababdbbe528690a07f4be372d917b20bba149ae09fe17fb9a0fb46

test:
  secret_key_base: 12bd70258fc16a7c47e8adb2b76064bb5bc964d5e4f768eec70d91a7a3f39dfa5269401581405863ad2921fa1cb2389890cb205d7799aa494df4c7570e1e8c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
